### PR TITLE
Detach continuations of AsyncOperationHandle from the Completed callback

### PR DESCRIPTION
**Pull request by foriequal0**
fixes: https://github.com/Cysharp/UniTask/issues/353

### CODE REVIEW

**Comment by neuecc** [comment]
Is it ok to change timing to PostLateUpdate?

**Comment by foriequal0** [comment]
I'm not sure about the timing. I wanted to make sure that the continuation would run as soon as possible.

**Comment by neuecc** [comment]
Oh, I see.
The timing in this was only used for Cancel and Progress checks, and the callback itself was sent out at the fastest possible time.
Sorry, I understand your PR.

However, I'm not comfortable with making this the default behavior for all AsyncOperationHandle.

**Comment by foriequal0** [comment]
I understand that. How about making it an opt-in?

**Comment by foriequal0** [comment]
Don't mind if you aren't comfortable with that option too. I can maintain a private fork or fix existing usages with an extension methods.
Also, would the closest time be LastPreLateUpdate rather than PostLateUpdate?

**Comment by neuecc** [comment]
WaitForCompletion is an operation that converts async to sync,
what is the reason for using sync-wait in UniTask?

**Comment by neuecc** [comment]
OK.
I think your code is a meaningful solution for those who will encounter the same problem in the future, thank you.
However, hacks cannot be added to the standard as a solution for bad practice.
I understand that hacks are sometimes necessary:)

**Pull request closed without merging**
