### PR TITLE
DoTween null reference on destroy fix

### PR DESCRIPTION
**Pull request by Akilaydin**
Greetings!
There is an issue, that throws DoTween null reference if destroying tweened GameObject, while the tween is still playing if using extension method GetCancellationTokenOnDestroy() and pass the given token to the AwaitForComplete()/ToUniTask()/WithCancellation() methods.

Here is an extension method that solves this problem and I want to merge it into the main branch.

```
var token = this.GetCancellationTokenOnDestroy();

transform.DOScale(Vector3.one, 2f).WithCancellation(token); //throws null reference on destroy
			
transform.DOScale(Vector3.one, 2f).AwaitForComplete(cancellationToken: token); //throws null reference on destroy
			
transform.DOScale(Vector3.one, 2f).ToUniTask(cancellationToken: token); //throws null reference on destroy
			
transform.DOScale(Vector3.one, 2f).AwaitWithCancellation(token); //Do not throw null reference on destroy
```

### CODE REVIEW

**Comment by ManuelRauber** [comment]
@neuecc Can we get this merged, also having the same issue. 

Thanks :)

**Comment by kondratov-saritasa** [comment]
@neuecc I vote for this one be merged too :)

**Comment by hadashiA** [comment]
refs: https://github.com/Cysharp/UniTask/issues/378

**Comment by hadashiA** [comment]
Hi,
We are working on this problem.

About this PR,
- The new methods you added are hard to see how they differ from the existing API. If you want to fix the behavior, it would be nice to improve it for all APIs.
- Also, it is possible to add extended methods without merging them into the main repo. 

So I'm sorry, but please let me Close.

 I hope the fix in #485 will fix this issue

**Pull request closed without merging**
