### PR TITLE
UniTask2

### PR DESCRIPTION
**Pull request by neuecc**
Brings completely zero allocation async/await to Unity, now.
---
Fully refactored(with many breaking changes).

- [x] Impl new AsyncMethodBuilder and CompletionSource
- [x] Modify UniTask.* methods
- [x] Modify Triggers
- [x] more PlayerLoopTiming(Initialization, LastInitialization, ... , PostLateUpdate, LastPostUpdate)
- [x] Rename namespace? ( `Cysharp.Threading.Tasks` ? )
- [x] Remove ValueTask
- [x] More UnitTest
  - [x] uGUI Events
  - [x] AsyncTriggres
  - [x] Preserve
  - [x] Debugger Attach
- [x] Remove Job's Cancellation
- [x] Preserve and AsyncLazy(ToAsyncLazy?)
- [x] Rethink PlayerLoop lifecycle(Play -> Editor -> Play) / related #50
- [x] .NET Core Edition
- [x] ObjectIdForDebugger to AsyncMethodBuilder
- [x] Rethink Unobseverved Exception Behaviour #40
- [x] Addressable Support? #45
- [x] AsyncStream #72
- [x] Project structure change https://github.com/Cysharp/UniTask/pull/61#issuecomment-625316639
- [x] GitHub Actions(remove CircleCI)
- [ ] Migration document
- [ ] Standard document

### CODE REVIEW

**Comment by neuecc** [comment]
I've released v2.0.0-preview1.
Please try.
https://github.com/Cysharp/UniTask/releases/tag/2.0.0-preview1

**Comment by kamyker** [comment]
Mixed feelings about how many methods generated WhenAll/WhenAny has.

How do we check "UniTask.IsCompleted"?

**Comment by neuecc** [comment]
> how many methods generated WhenAll/WhenAny have. 

The default number of Func.
If there are too many of them, IntelliSense becomes heavy, so I thought that this level is enough for practical use.
If you want to use more than this, you can use the WhenAll array (for different types, you will need to combine Preserve and AsUnitTask)

> UniTask.IsCompleted

use `UniTask.Status` and there extension methods(`IsCompleted`, `IsCompletedSuccessfully`, `IsFauleted`, `IsCanceled`).
For example
`task.Status.IsCompleted()`.

**Comment by bdovaz** [comment]
@neuecc Please in order to better integrate UPM, follow package layout convention:

https://docs.unity3d.com/Manual/cus-layout.html

Now you have the code distributed inside the Assets folder.

**Comment by neuecc** [comment]
@bdovaz 
Setting the UPM recommendations will break the layout in .unitypackage.
In any case, root is not going to be the root of this repository (it doesn't support anything other than the use of PATH since 2019.3.4f1)

There is a slight inconvenience in either, due to the fact that it is provided in both .unitypackage and UPM.
Is there any reason why the UPM layout must absolutely match the recommendations?

**Comment by bdovaz** [comment]
@neuecc 

Reading the UniTask2 release notes I see that there are multiple breaking changes so I don't see the problem in the folder structure changing, it's just another breaking change to the list.

For me it's the right time to put the UniTask2 code in:

Assets
Packages
  com.cysharp.unitask2
    Editor
    Runtime
    -- (Other package layout convention files)

In this way it is much clearer, it is a "real" package and it undergoes the checks that Unity does with packages such as that all code is included in a *.asmdef and other validations like those of this package:

https://docs.unity3d.com/Packages/com.unity.package-validation-suite@0.9/manual/index.html

**Comment by neuecc** [comment]
current v2's structure.

```
github.com/Cysharp/UniTask
- src
  - UniTask
    - Assets
      - Plugins
        - UniTask
          - package.json
          - source_codes
```

under the package.json root, okay to modify.

```
github.com/Cysharp/UniTask
- src
  - UniTask
    - Assets
      - Plugins
        - UniTask
          - package.json
          - ReadMe.md(copy and sync from root)
          - Runtime
          - Editor
```

**Comment by neuecc** [comment]
Stop release track.
Require to complete #73.

**Comment by bdovaz** [comment]
> current v2's structure.
> 
> ```
> github.com/Cysharp/UniTask
> - src
>   - UniTask
>     - Assets
>       - Plugins
>         - UniTask
>           - package.json
>           - source_codes
> ```
> 
> under the package.json root, okay to modify.
> 
> ```
> github.com/Cysharp/UniTask
> - src
>   - UniTask
>     - Assets
>       - Plugins
>         - UniTask
>           - package.json
>           - ReadMe.md(copy and sync from root)
>           - Runtime
>           - Editor
> ```

I see that you are working on this.

I didn't see your tests folder but according to Package layout page you should include Tests inside that structure:

https://docs.unity3d.com/Manual/cus-layout.html

- src
  - UniTask
    - Assets
      - Plugins
        - UniTask
          - package.json
          - README.md
          - CHANGELOG.md
          - LICENSE.md
          - Runtime
          - Editor
          - Tests
            - Editor
            - Runtime

**Comment by neuecc** [comment]
We don't include unit tests right now because there are so many of them on the .NET Core side and Unity-only measurements don't give accurate values.
We will look into it in the future.

**Comment by neuecc** [comment]
released preview4, please try it.
https://github.com/Cysharp/UniTask/releases/tag/2.0.3-preview4

**Comment by neuecc** [comment]
released 2.0.4-rc1.
(maybe) this is the final preview.

**Comment by KAW0** [comment]
I think "Cysharp.Threading.Tasks" is too long. You can't just use just "Cysharp.Tasks"?

**Comment by neuecc** [comment]
released 2.0.5-rc2.

Yes, this namespace is long, but I won't change it unless there's a specific reason to do so because it's similar with System.Threading.Tasks.

**Comment by neuecc** [comment]
released 2.0.6-rc3.
I hope this will be final rc.

**Comment by KAW0** [comment]
Will it be possible to use new unitask in the editor code? Some time ago Unity created a package that allows the use of coroutins in the editor. This can be helpful: [https://docs.unity3d.com/Packages/com.unity.editorcoroutines@0.0/manual/index.html](https://docs.unity3d.com/Packages/com.unity.editorcoroutines@0.0/manual/index.html)

**Comment by neuecc** [comment]
after 1.3.0, already supports editor mode.

**Comment by neuecc** [comment]
released 2.0.7-rc4.

**Comment by neuecc** [comment]
released 2.0.8-rc5.

**Comment by neuecc** [comment]
2.0.9-rc6

**Comment by neuecc** [comment]
2.0.10-rc7

**Comment by neuecc** [comment]
2.0.11-rc8(rc???)

**Comment by neuecc** [comment]
Thank you for all contributors, now I've released stable v2.

**Pull request merged**
