### PR TITLE
Add AsyncInstantiate support

### PR DESCRIPTION
**Pull request by ilakhin**
https://docs.unity3d.com/2023.3/Documentation/ScriptReference/AsyncInstantiateOperation_1.html

### CODE REVIEW

**Comment by neuecc** [comment]
What is `UNITASK_ASYNCINSTANTIATE_SUPPORT`?

**Comment by ilakhin** [comment]
AsyncInstantiateOperation was added since Unity 2022.3.20 / 2023.3.0b7:
- https://unity.com/releases/editor/whats-new/2022.3.20
- https://unity.com/releases/editor/beta
I didn't find a define like UNITY_2022_3_20_OR_NEWER to restrict the methods.

**Comment by timcassell** [comment]
Unity doesn't add new APIs in patch versions. It was added in 2022.3.0, so you can use UNITY_2022_3_OR_NEWER

**Comment by ilakhin** [comment]
Unity 2022.3.19f1 does not support this API. It was added in a patch version (https://unity.com/releases/editor/whats-new/2022.3.20).
image

**Comment by timcassell** [comment]
Oh I missed it in the notes because of the weird formatting. `Player: Added: Object.InstantiateAsync&lt;T&gt;().`... Ugh, Unity doing stupid things so much.

**Comment by Torgo13** [comment]
There is a new define in 2022.3.20f1 that can be used instead of #if UNITASK_ASYNCINSTANTIATE_SUPPORT:
#if UNITY_2022_3_20

I assume it's supposed to be #if UNITY_2022_3_20_OR_NEWER, but we'll know for sure once 2022.3.21f1 comes out.

**Comment by nansofting** [comment]
I've come up with the following define. It's not elegant but it does what you want.
```csharp
// 2022.3.20f1 or newer
#if UNITY_2022_3_OR_NEWER && !(UNITY_2022_3_0 || UNITY_2022_3_1 || UNITY_2022_3_2 || UNITY_2022_3_3 || UNITY_2022_3_4 || UNITY_2022_3_5 || UNITY_2022_3_6 || UNITY_2022_3_7 || UNITY_2022_3_8 || UNITY_2022_3_9 || UNITY_2022_3_10 || UNITY_2022_3_11 || UNITY_2022_3_12 || UNITY_2022_3_13 || UNITY_2022_3_14 || UNITY_2022_3_15 || UNITY_2022_3_16 || UNITY_2022_3_17 || UNITY_2022_3_18 || UNITY_2022_3_19)
```

**Comment by xtutu** [comment]
is there any progress?  we need it

**Comment by Thordreck** [comment]
What's the expected behaviour when the extensions introduced in this PR are used with an `AsyncInstantiateOperation` with the `allowSceneActivation` flag set to false? From what I have understood looking at the code the task would never complete.

**Comment by neuecc** [comment]
`AsyncInstantiateOperation` is `AsyncOperation` so I think no need to special care.
I think you can use await and `ToUniTask` without doing anything, but is there a problem?

**Comment by neuecc** [comment]
ah ok, ToUniTask can not get return value, https://github.com/Cysharp/UniTask/issues/622

**Comment by neuecc** [comment]
v2.5.9 support it.

**Pull request closed without merging**
