### PR TITLE
Optimize ContinuationQueue and PlayerLoopRunner iteration

### PR DESCRIPTION
**Pull request by RamType-0**
- Fix failing to eliminate array bounds check in PlayerLoopRunner.RunCore
- Reduce number of array bounds check of continuation iteration in ContinuationQueue.RunCore

### CODE REVIEW

**Comment by neuecc** [comment]
> Fix failing to eliminate array bounds check in PlayerLoopRunner.RunCore

Okay, thanks.

> Reduce number of array bounds check of continuation iteration in ContinuationQueue.RunCore

I don't know ref ref can reduce bounds check.
Do you have any evidence?

**Comment by RamType-0** [comment]
> I don't know ref ref can reduce bounds check.
> Do you have any evidence?

I tried to create evidence benchmark.
#150 
But I got weird result.
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.450 (2004/?/20H1)
Intel Core i9-9900K CPU 3.60GHz (Coffee Lake), 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.100-preview.8.20417.9
  [Host]   : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT
  ShortRun : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT

Job=ShortRun  IterationCount=1  LaunchCount=1  
WarmupCount=1  

```
|                         Method |     Mean | Error |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------- |---------:|------:|-------:|------:|------:|----------:|
|                     WithoutRef | 120.5 μs |    NA | 0.3662 |     - |     - |   3.13 KB |
|        WithoutRefNoBoundsCheck | 121.7 μs |    NA | 0.3662 |     - |     - |   3.13 KB |
|       WithoutRefLocalListCount | 121.9 μs |    NA | 0.3662 |     - |     - |   3.13 KB |
|                        WithRef | 120.2 μs |    NA | 0.3662 |     - |     - |   3.13 KB |
|           WithRefNoBoundsCheck | 121.1 μs |    NA | 0.3662 |     - |     - |   3.13 KB |
|          WithRefLocalListCount | 120.1 μs |    NA | 0.3662 |     - |     - |   3.13 KB |
|               WithoutRefWraped | 139.8 μs |    NA | 0.4883 |     - |     - |      5 KB |
|  WithoutRefNoBoundsCheckWraped | 138.0 μs |    NA | 0.4883 |     - |     - |      5 KB |
| WithoutRefLocalListCountWraped | 136.4 μs |    NA | 0.4883 |     - |     - |      5 KB |
|                  WithRefWraped | 139.2 μs |    NA | 0.4883 |     - |     - |      5 KB |
|     WithRefNoBoundsCheckWraped | 136.8 μs |    NA | 0.4883 |     - |     - |      5 KB |
|    WithRefLocalListCountWraped | 139.5 μs |    NA | 0.4883 |     - |     - |      5 KB |

Where is this different amount of allocation comes from??

I gonna revert change for Continuation.RunCore this time.

**Comment by RamType-0** [comment]
According to benchmark, at least using ref Action to raw array element is not performant.
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.450 (2004/?/20H1)
Intel Core i9-9900K CPU 3.60GHz (Coffee Lake), 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.100-preview.8.20417.9
  [Host]     : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT
  Job-UBSNUT : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT

InvocationCount=1  UnrollFactor=1  

```
|                         Method |                    Categories |     Mean |    Error |   StdDev |   Median |
|------------------------------- |------------------------------ |---------:|---------:|---------:|---------:|
|                     WithoutRef |          WithoutRef,RawAction | 29.84 ms | 0.254 ms | 0.225 ms | 29.77 ms |
|        WithoutRefNoBoundsCheck |          WithoutRef,RawAction | 27.16 ms | 0.181 ms | 0.151 ms | 27.20 ms |
|       WithoutRefLocalListCount |          WithoutRef,RawAction | 30.28 ms | 0.172 ms | 0.152 ms | 30.28 ms |
|                        WithRef |             WithRef,RawAction | 53.41 ms | 0.264 ms | 0.221 ms | 53.34 ms |
|           WithRefNoBoundsCheck |             WithRef,RawAction | 53.23 ms | 0.267 ms | 0.250 ms | 53.27 ms |
|          WithRefLocalListCount |             WithRef,RawAction | 53.40 ms | 0.165 ms | 0.138 ms | 53.39 ms |
|               WithoutRefWraped | WithoutRef,StructWrapedAction | 31.43 ms | 0.593 ms | 1.302 ms | 30.86 ms |
|  WithoutRefNoBoundsCheckWraped | WithoutRef,StructWrapedAction | 26.25 ms | 0.298 ms | 0.233 ms | 26.24 ms |
| WithoutRefLocalListCountWraped | WithoutRef,StructWrapedAction | 27.61 ms | 0.546 ms | 0.629 ms | 27.61 ms |
|                  WithRefWraped |    WithRef,StructWrapedAction | 39.87 ms | 0.156 ms | 0.138 ms | 39.90 ms |
|     WithRefNoBoundsCheckWraped |    WithRef,StructWrapedAction | 30.99 ms | 0.119 ms | 0.099 ms | 30.97 ms |
|    WithRefLocalListCountWraped |    WithRef,StructWrapedAction | 34.37 ms | 0.597 ms | 0.498 ms | 34.57 ms |

I aborted change to ContinuationQueue.RunCore.

**Comment by neuecc** [comment]
should remove `//Reduce array bounds check` comment, too.

**Pull request merged**
