### PR TITLE
docs: update installation options and the openupm badge

### PR DESCRIPTION
**Pull request by favoyang**
Hi @neuecc,

Thanks for making the great upm package. I'm the creator of [OpenUPM](https://openupm.com) platform, an open-source UPM registry and continuous build service based on Git tags. So far it's hosting more than 180+ UPM packages.

Your package is elegant. I have submitted it to the platform.  https://openupm.com/packages/com.cysharp.unitask/

Here's the update for installation options and the badge, please consider to merge.

### CODE REVIEW

**Comment by neuecc** [comment]
Thanks, I think it is useful registry.
Right now I'm doing a big change for v2, how does UPM automate the release?
I'm worried if It'll be followed properly.

**Comment by favoyang** [comment]
Hi @neuecc,

The process can be roughly described as below,
- OpenUPM tracks Git tags that confirm semver every 5 minutes. You can optionally control the behavior using a prefix match and/or a regular expression match. See `gitTagPrefix` and `gitTagIgnore` in [package YAML file](https://openupm.com/docs/adding-upm-package.html#package-yaml-file).
- It checks out and Git tag, and locate the `package.json` path, then build the package from here.

e.g.
https://openupm.com/packages/com.cysharp.unitask/

image

For some authors who want to run some customizations (e.g. moving docs, samples...) about their upm release, a common practice is
- Do regular GitHub release with Git tag name `x.y.z`.
- Create an update-to-date upm branch, run some customizations (via CI or manually), then tag it as `upm/x.y.z`).
- Set `gitTagPrefix` to `upm/`, then the OpenUPM will only track tags with `upm/` prefix.

Which way to go is case to case. So far your repository have a [trivial setup](https://github.com/openupm/openupm/blob/master/data/packages/com.cysharp.unitask.yml) and works well.

Let me know if this makes sense for your project.

**Comment by favoyang** [comment]
@neuecc,
I noticed your latest 2.0.0 preview tag. It failed with reason "version conflict" because you forget to update the version of [package.json](https://github.com/Cysharp/UniTask/blob/5f90807cb761a9125e7ca3a95ddc1178cccc79c4/src/UniTask/Assets/Plugins/UniTask/package.json).

image

For the failed tag, you can just fix the issue, then retag it, OpenUPM will detect it and rebuild it for you.

However, if you released a successful version, then you changed your mind, wanner to retag it (so-called republish an existing version). This is not allowed for OpemUPM (and other public registries like NPM). You will help to bump the version (tag a new version) to fix it, For more information, please checkout https://github.com/openupm/openupm/issues/134

**Comment by neuecc** [comment]
Thank you, I could see v2.0.3-preview listed for sure.
I also found OpenUPM to be a great way to work.
I'll be including the guide in the soon-to-be-released v2 ReadMe.

**Comment by neuecc** [comment]
Now, I've released v2 and that document includes link to OpenUPM you provided.

**Pull request closed without merging**
